# Generated by Django 5.1.5 on 2025-03-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
